# 볼륨 초기화: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml down -v
# 실행: docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up --build
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - personal_blog_db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  personal_blog_db_data:
    external: true
